version: '3'
services:
  site:
    container_name: ${SITE_CONTAINER_NAME}
    build: ./site
    volumes:
      - ./site:/var/www/html
    environment:
      USERS_CONTAINER_NAME: ${USERS_CONTAINER_NAME}
    tty: true
    restart: always
    env_file:
      - ./.env
  users:
    container_name: ${USERS_CONTAINER_NAME}
    build: ./users
    volumes:
      - ./users:/var/www/html
    tty: true
    restart: always
    env_file:
      - ./.env
