version: '3'
services:
  site:
    container_name: ${SITE_CONTAINER_NAME}
    build: ./site
    ports:
      - "${PORT}:80"
    volumes:
      - ./site:/var/www/html
    environment:
      RUN_SCRIPTS: 1
      USERS_CONTAINER_NAME: ${USERS_CONTAINER_NAME}
      SITE_CONTAINER_NAME: ${SITE_CONTAINER_NAME}
  users:
    container_name: ${USERS_CONTAINER_NAME}
    build: ./users
    volumes:
      - ./users:/var/www/html
    environment:
      RUN_SCRIPTS: 1
      SITE_CONTAINER_NAME: ${SITE_CONTAINER_NAME}
      USERS_CONTAINER_NAME: ${USERS_CONTAINER_NAME}
